### ISSUE TITLE
Protocol version 37 is not supported.

### ISSUE THREAD

**Issue by hassansheikh** [Ostico/PhpOrient#102]
I'm trying to create the connection and getting exception
Protocol version 37 is not supported.

Code:
$client = new PhpOrient( 'localhost', 2424 );
$client->connect( 'root', 'password' );

**Comment by mtveerman** [comment]
This is because you use OrientDB 3. See #99 
You could fall back to OrientDB 2.2

**Comment by hassansheikh** [comment]
I have fixed issue by setting protocol version with 30.

**Comment by hassansheikh** [comment]
I have fixed issue by setting protocol version with 30.

**Comment by Ostico** [comment]
Released v1.3.0, it is tested and works with OrientDB 3.x
