### ISSUE TITLE
Fatal error: Allowed memory...

### ISSUE THREAD

**Issue by odiel** [Ostico/PhpOrient#25]
Hi,

I'm doing some functional tests in my application and I'm running some fixtures before the tests, so I can check if the logic part of the application is doing the right job, then from withing the tests I'm checking the modified data. Sometimes the test suit goes through without any interruption but some other times it shows this fatal error:

    Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1869426288 bytes) in .../vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/OrientSocket.php on line 136

it is very random, and I'm not able to find yet what may be causing it, probably somebody is having something similar.

**Comment by andreyvk** [comment]
The number of bytes it was trying to allocate is particularly large (~1.7GB). Do you at least know which test causes it?

**Comment by Ostico** [comment]
Hi @andreyvk , i don't know what kind of tests are you running. I can't help you this way.

Can you provide me some part of code or you can send me the rest of the stack trace?

Today i will check for  tour issues.

**Comment by odiel** [comment]
Hi guys,

Yesterday I found what could possibly be the issue, but had not enough time to provide details since I have the code at work, I'll try to get back to  you on Monday.

**Comment by Ostico** [comment]
OK, i will try to fix as soon and possible.

**Comment by odiel** [comment]
I remember it had to do with the "Unknown payload type issue", since I was trying to remove a class that didn't exists (that of course raised an exception that was catched) , and right after that I executed TRUNCATE CLASS "another class," and that raised the "Unknown payload type issue", at this point the class I was trying to truncate existed but had nothing inside, then after that I got the socket fatal error for the next query. I would show more details about the code on Monday.

**Comment by Ostico** [comment]
Right, thanks.

**Comment by Ostico** [comment]
Odiel i think this was related to:

[Unknown payload type issue #22](https://github.com/Ostico/PhpOrient/issues/22)

I think now should work. 
Try the new release and let me know.

**Comment by odiel** [comment]
Hi @Ostico 

Yes, both issues are fixed now. Really appreciated your speed.
