### ISSUE TITLE
Error after update Orientdb

### ISSUE THREAD

**Issue by luclanet** [Ostico/PhpOrient#27]
PHP Fatal error:  Uncaught exception 'PhpOrient\\Exceptions\\PhpOrientWrongProtocolVersionException' with message 'Protocol version 30 is not supported.'

**Comment by luclanet** [comment]
If you remove #91 to #93 on
PhpOrient/Protocols/Binary/OrientSocket.php

it works perfectly.

```if( $protocol > $this->protocolVersion ){
                throw new PhpOrientWrongProtocolVersionException('Protocol version ' . $protocol . ' is not supported.');
            }```

**Comment by Ostico** [comment]
Hi @luclanet , PhpOrient only supports the Orientdb stable releases.

What version you are using?

**Comment by luclanet** [comment]
orientdb-community-2.1-rc3

**Comment by Ostico** [comment]
You can use the last stable 2.0.10 version and all the preeceding versions.
