### ISSUE TITLE
Saving date field loses date data

### ISSUE THREAD

**Issue by andreyvk** [Ostico/PhpOrient#29]
Hi,

I think there's a problem saving date/datetime fields, while updating records. Looks like problem is with converting DateTime object into date data, when saving a record. Im on the latest PhpOrient using OrientDB 2.0.10.

Here's the schema + test record:

```
create class Test extends V

create property Test.date date

insert into Test set date = "2015-01-01"
```

In the console:

```
orientdb {db=test}> select from Test

----+-----+------+-------------------
#   |@RID |@CLASS|date
----+-----+------+-------------------
0   |#43:0|Test  |2015-01-01 00:00:00
----+-----+------+-------------------
```

Executing the following saves wrong date data:

```php
$client = new \PhpOrient\PhpOrient( 'localhost', 2424 );
$client->username = 'user';
$client->password = 'pass';
$client->connect();
$client->dbOpen( 'test', 'user', 'pass' );
$record = $client->recordLoad( new \PhpOrient\Protocols\Binary\Data\ID( '#43:0' ) )[0];
$updatedRecord = $client->recordUpdate( $record );
```

Select again (see date data lost): 

```
orientdb {db=test}> select from Test

----+-----+------+-------------------
#   |@RID |@CLASS|date
----+-----+------+-------------------
0   |#43:0|Test  |1970-01-17 00:00:00
----+-----+------+-------------------
```

**Comment by Ostico** [comment]
Thenk you @andreyvk , i will investigate

**Comment by andreyvk** [comment]
I'm happy I could help really. And thanks for great job on this library :)

**Comment by pjmazenot** [comment]
Hi, I had the same problem with DateTimes and fixed it (for now), by replacing this line:

`return $value->getTimestamp() . 't';`

by this one:

`return $value->getTimestamp() . '000t';`

(vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/Serialization/CSV.php:530)

Hope that helps!

**Comment by Ostico** [comment]
Hi @pjmazenot ,

the patch you suggested is good. I'm updating.

**Comment by pjmazenot** [comment]
Glad I could help. 
Thanks @Ostico for this library, I just started using OrientDB and it saved me a lot of time!

**Comment by andreyvk** [comment]
Thanks @pjmazenot! Looking forward for an official patch
