### ISSUE TITLE
Protocol version 30 

### ISSUE THREAD

**Issue by bbgg91** [Ostico/PhpOrient#30]
I may be missing something but I am testing with 2.1 rc3 and when I try to open the data connection I get 

PHP Fatal error: Uncaught exception 'PhpOrient\Exceptions\PhpOrientWrongProtocolVersionException' with message 'Protocol version 30 is not supported.' in C:\inetpub\wwwroot\sim2me\orientdb\src\PhpOrient\Protocols\Binary\OrientSocket.php:92 Stack trace: #0 

Is this version compatible with 2.1 rc3 or should I wind back?

Many Thanks Ben

**Comment by Ostico** [comment]
Hi @bbgg91 , rc3 is not yet supported ( will be soon ), you can try with rc2, 2.0.10 versions, they  works.

**Comment by smolinari** [comment]
Buggers. What is missing or rather, how long will the wait be for 2.1 support?

Scott

**Comment by smolinari** [comment]
Is the the newest fork or should I be using the Oriento fork?

Also, I downgraded my OrientDB instance to 2.0.10 and the token unit tests are still failing. I used the skip logic to pass up the ConnectTokenTest and everything else seems to be working. I wasn't able to find out why the token tests were failing.

Scott

**Comment by Ostico** [comment]
Hi @smolinari ,
Yes this is the right repository.
Regarding the token issue, in order to use the token based authentication, this functionality must be enabled on the server config.

Look at this there to have an idea:
https://github.com/Ostico/PhpOrient/blob/master/ci/orientdb-server-config_2.0.xml#L76

**Comment by smolinari** [comment]
Thanks Domenico, 

I had found the token setting, but when I enabled it, the tests still failed. Not only that, but then the Studio stopped working too.

What is the difference between this repo and the OrientDB's fork? I cloned it, but it seems to have your last updates too.

Scott

**Comment by smolinari** [comment]
Oh, and what needs to be looked at or done to get the driver up to API 31?

Scott

**Comment by smolinari** [comment]
I've fixed the token issue and all tests are running and passed. It was a stupid mistake on my part, or rather, lack of knowledge about the token system from ODB. The oAuth key wasn't set. Silly me to think it should work without it.

I'd still like to know what needs to be looked at, to get API 31 working, if anyone could point me in the right direction, I'd very obliged.

Scott

**Comment by adamgoose** [comment]
With the release of 2.1-rc5, the new protocol version is 31.

**Comment by dcarr178** [comment]
Now that orientdb 2.1.0 is GA, phporient is incompatible saying Protocol version 30 is not supported. Any workaround?

**Comment by smolinari** [comment]
I'd like to know this too please. :+1: I'd like to know what is missing. Maybe I can help. 

Scott

**Comment by Ostico** [comment]
Hi all, 

i'm working to update the support to the newest protocols.

**Comment by smolinari** [comment]
Fantastic Domenico! :+1: Thank you! :smile: 

Scott
