### ISSUE TITLE
Why "good enough"?

### ISSUE THREAD

**Issue by smolinari** [Ostico/PhpOrient#32]
In the readme.md it reads....

 >A PHP driver good enough for OrientDB that uses binary protocol.

Why "good enough"? Could it be better? Is something missing? Is the quality poor?

Scott

**Comment by Ostico** [comment]
Hi @smolinari ,

I hope that the quality is little bit better than poor.

By the way, everything could be better, and surely talking about software the perfection does not exists and never will exist. So, i repeat, i think this is a good enough driver for orientDB and i will try to improve it even more.

**Comment by smolinari** [comment]
Ok. So what do you think needs to happen, so this driver is "good", or even "very good"?

My only concern is for the popularity of the driver. If people, like me, read the "good enough" it sounds like the quality is lacking in some way. Surely, software can almost always be improved. However, if a software is good, it should be said to be good and not "good enough".

I'd like to read, 

 >PHPOrient is a very good php driver based on the binary protocol of OrientDB.

Scott

**Comment by smolinari** [comment]
:+1: 

Scott
