### ISSUE TITLE
[Question] OutOfBoundsException in Record::offsetGet()

### ISSUE THREAD

**Issue by andreyvk** [Ostico/PhpOrient#38]
Hi @Ostico,

Why is it necessary to trigger an exception in `Record::offsetGet()` and not just return`null` by default? In case if this behavior is necessary, is it possible to add an option to the client that allows suppressing `OutOfBoundsException` for unknown record indices?

**Comment by Ostico** [comment]
@andreyvk , accepdet. I removed the ```OutOfBoundsException```
