### ISSUE TITLE
Error 115 : Operation now in progress

### ISSUE THREAD

**Issue by tellyarz** [Ostico/PhpOrient#43]
I was trying to make an API request to my OrientDB server with the PHPOrient library and getting the following error message: "Error 115: Operation now in progress" I am using the Enterprise 2.1.0 version

**Comment by tellyarz** [comment]
Okay, I noticed that this error occurs when a client with https is making request from an http server(orientDB installed here)

**Comment by Ostico** [comment]
Hi @tellyarz ,

can you explain better your issue?

Thank you in advance

**Comment by tellyarz** [comment]
I have a server containing OrientDB enterprise edition and a client where PhpOrient is installed. I am trying to access and retrieve items in the OrientDB with PhpOrient from the client but I got

"Error 115: Operation now in progress"

The client is hosted with an https domain. 

I later tried to access and retrieve items using a client with an http domain and did not get the error, everything worked fine. So, I was wondering if there was a problem with https domain and PhpOrient

**Comment by Ostico** [comment]
I think this is not related to the client, the client is not aware of the web server configuration.

I think you have some kind of firewall in the server that hosts OrientDB

Can you post an example of your PhPClient configuration ( of course, mask the not disclosable parts )

**Comment by tellyarz** [comment]
I think you are right. the server is in a Virtual Private Cloud, so what I did was to install PhpOrient on the server that contain the OrientDB and this works fine.
