### ISSUE TITLE
Create Edge using RecordCreate doesn't seem to be working.

### ISSUE THREAD

**Issue by sptutusukanta** [Ostico/PhpOrient#49]
What I need, is to do transaction with edges. In my application I've used the RecordCreate, Record Delete and RecordUpdate Methods without using of command or query method.

So, I use the Transaction Statement and attach the Operations to it. But, at this point of time I need a way to create Edges and attach it to Transaction Statement.

I know I can go for Batch Query using the query method. But, my app is dynamic and I need to do Transaction at any point. If I choose to go for Batch Query, all the procedures of it, had to be changed.

Please Help!

**Comment by Ostico** [comment]
Hi @sptutusukanta ,

sotty, but the bynary protocol does not support a method for the edge creation, so you have to create manually the edges ( they are records in the E class or it's children ) and after you must create the connections.

**Comment by sptutusukanta** [comment]
Yes, I've tried to create edge using the recordCreate. You are right, the record is getting created as Edge but not linking it to the vertexes. Can you please help how to achieve that?
Also, is it possible to attach that Operation to a Transaction Statement.

Thanks, for your support.

**Comment by sptutusukanta** [comment]
Also, as you say "binary protocol does not support a method for the edge creation", is there any hope it will be added in near future and you update those in this module.

**Comment by Ostico** [comment]
Can i close this?
