### ISSUE TITLE
 Invalid argument supplied for foreach() in getNodesList

### ISSUE THREAD

**Issue by ncreea** [Ostico/PhpOrient#51]
I recently updated our OrientDB to 2.1.3 and had to update the library (to the latest via composer) too. Now in logs I see a few PHP Warnings like below, but It's not happening all the time:

>Invalid argument supplied for foreach() in /vendor/ostico/phporient/src/PhpOrient/Protoco ls/Common/AbstractTransport.php on line 154

**Comment by pentium10** [comment]
We have the same issue? any update on this @Ostico ?
As it looks it happens with today's composer build too.

**Comment by ncreea** [comment]
Update: This Warning is generated when a query times out.

**Comment by andreyvk** [comment]
Is this issue causing any undesired behavior? 

According to the code, list of nodes is a bunch of orientdb distributed nodes. So possibly that list is empty, if there's a timeout, thus causing the warning.

**Comment by ncreea** [comment]
No, it seams that is not causing any undesired behavior other then filling up the error_log and sending out email alerts in case you have email alerts on error logs enabled.

**Comment by andreyvk** [comment]
I see. Would be nice to fix that eventually of course. Hope @Ostico can get to that as soon as he can

**Comment by pentium10** [comment]
I hope @Ostico will have time to fix the multiple issues reported with the library lately, as more and more people start using on production servers

**Comment by Ostico** [comment]
Yes guys, this weekend i will try to fix your issues. Btw, can you provide more info on how reproduce your issues, more environment info and code snippets? Tnx in advance

**Comment by ncreea** [comment]
Reproduce: Try to execute any SELECT query any any system you have, but make sure you set a TIMEOUT lower then Orient is able to execute it.

**Comment by Ostico** [comment]
Fixed in next release.
