### ISSUE TITLE
how can in fix Timezone of date

### ISSUE THREAD

**Issue by jackraj88** [Ostico/PhpOrient#54]
Hi,
i am using  odb - 1.7.11,  phporient  - 1.0

In database inserted record Asia/kolkata timezone but using ostico phporient driver retrieve record from database timezone will be differ. how can i fix it.

**Comment by smolinari** [comment]
I believe you have to account for timezone differences in your application. Basically, you'd need to save the time according to UTC, then recalculate the time according to the user's own time zone.

**Comment by andreyvk** [comment]
I would usually set server's timezone to UTC so that I know how to quickly
convert from saved date into a date displayed to a client

**Comment by smolinari** [comment]
Right. That is what I also meant. LOL! Obviously, the clock you get the current time from to save would also need to be set to UTC. :smile: 

Scott

**Comment by Ostico** [comment]
Thank you @andreyvk and @smolinari for support. I close.

**Comment by andreyvk** [comment]
Anytime @Ostico! ))
