### ISSUE TITLE
PHP 7: Uninitialized string offset: 0

### ISSUE THREAD

**Issue by ctoesca** [Ostico/PhpOrient#58]
Since I have upgraded PHP (v7), when I insert a vertex (with command() method) , I have this error:
Uninitialized string offset: 0

The vertex is well created.
The vertex I send is:

```
    Array ( [message] => TEST ORIENT [id] => 1 ) 
```

No problem with SELECT queries.

**Comment by ctoesca** [comment]
I patched CSV.php:
line 227:
if ($length > 1)
      $input = substr( $input, $i );

But I don't know if it's the right way.

**Comment by smolinari** [comment]
@ctoesca - have you run into any other issues with PHP7?

Scott

**Comment by ctoesca** [comment]
No other issues. 
But I use only <b>command()</b> and <b>query()</b> methods.

**Comment by smolinari** [comment]
Thanks for the info!

Scott

**Comment by bazo** [comment]
i have this same issue with select queries, some queries would throws this error
also queries that executed ok, didn't have all data. when i ran the same sql in webadmin, all the data was here
i downgraded to 1.2.3 nad this problem disappeared

**Comment by redstrike** [comment]
Will this issue be fixed? PHP 7 is the future, so I cannot leave it and back to PHP 5.6.

**Comment by Ostico** [comment]
Hi all. these days i will look for php7 compatibility.

@ctoesca i will review/test your patch

**Comment by haiflive** [comment]
The same error on query (DEFAULT VALUES)
`INSERT INTO Goods CONTENT {"@class":"Goods","@version":0,"@rid":"#-1:-1"}`

CSV.php
line 32

```
if(!empty($input)) {
    $chunk              = self::eatKey( $input );
    $key                = $chunk[ 0 ];
    $input              = $chunk[ 1 ];
 }
```

I test this framework on PHP7, yet found only this two bugs

**Comment by thenatsky** [comment]
@ctoesca adding that 'if' statement has side effects later on the function.  In the original code, $input is being overwritten to contain the "rest" of the param $input after a break in the for loop before.

There's logic afterwards that is using the now cutdown $input (the left-overs) but with your added if statement, that code is processing the original string, not the cutdown version.

Perhaps the if statement should encompass the rest of the code until just before the return?

**Comment by Ostico** [comment]
Php 7 supported in [v1.2.5](https://github.com/Ostico/PhpOrient/releases/tag/v1.2.5)
