### ISSUE TITLE
Protocol version 32 is not supported

### ISSUE THREAD

**Issue by bbgg91** [Ostico/PhpOrient#60]
Was this problem fixed? Upgraded to version 2.1.9 and have this error again. Updated the latest phporient to no avail.

**Comment by andreyvk** [comment]
It was. You can see PhpOrient/src/PhpOrient/Configuration/Constants.php. Have you double checked that your PhpOrient version is the latest?

**Comment by bbgg91** [comment]
Yep checked that and everything is up to date. Re booted and still have the problem.

**Comment by andreyvk** [comment]
I'll update to 2.1.9 and let you know. Also just to make sure: your `composer.json` in the PhpOrient root dir. Does it say that your version is 1.2.3?

**Comment by bbgg91** [comment]
So sorry... found the problem (mine) so all ok.

**Comment by andreyvk** [comment]
Great! @Ostico can you close the issue plz?

**Comment by Ostico** [comment]
Great.

Tnx @andreyvk
