### ISSUE TITLE
Fatal Error: Could not initialize class sun.security.util.SecurityConstants

### ISSUE THREAD

**Issue by sameer-shelavale** [Ostico/PhpOrient#69]
```
<br />
<b>Fatal error</b>:  Uncaught exception 'PhpOrient\Exceptions\PhpOrientException' with message 'java.lang.NoClassDefFoundError: Could not initialize class sun.security.util.SecurityConstants' in /home/snbo/production/snbo.com/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/Abstracts/Operation.php:412
Stack trace:
#0 /home/snbo/production/snbo.com/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/Abstracts/Operation.php(142): PhpOrient\Protocols\Binary\Abstracts\Operation-&gt;_readError()
#1 /home/snbo/production/snbo.com/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/Abstracts/Operation.php(217): PhpOrient\Protocols\Binary\Abstracts\Operation-&gt;_readHeader()
#2 /home/snbo/production/snbo.com/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/SocketTransport.php(154): PhpOrient\Protocols\Binary\Abstracts\Operation-&gt;getResponse()
#3 /home/snbo/production/snbo.com/vendor/ostico/phporient/src/PhpOrient/PhpOrient.php(287): PhpOrient\Protocols\Binary\SocketTransport-&gt;execute('command', Array)
#4  in <b>/home/snbo/production/snbo.com/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/Abstracts/Operation.php</b> on line <b>412</b><br />
```
I am getting above error on my production server. 
However same code runs fine on dev server.
**production server:**
phporient: 1.1.8
Orientdb: 2.1.0
java version "1.7.0_99"
OpenJDK Runtime Environment (rhel-2.6.5.0.el6_7-x86_64 u99-b00)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**dev server:**
phporient: 1.1.8
Orientdb: 2.1.0
java version "1.7.0_85"
OpenJDK Runtime Environment (rhel-2.6.1.3.el6_7-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)

How do I solve this bug?

**Comment by andreyvk** [comment]
Hi,

Doesnt look like PhpOrient error to me. Maybe something to do with JRE? How
about moving to Oracle JRE instead?

**Comment by Ostico** [comment]
Hi @sameer-shelavale ,

this is an error inside OrientDB dued to a Class Not Found Exception:
```java.lang.NoClassDefFoundError```

This could be related to your SQL statement maybe, but not directly related to the PHP Client.

Can you show the query you executed?

**Comment by sameer-shelavale** [comment]
This was happening as I was using old version(1.1.8) of PhpOrient
The error vanished after i upgraded to latest version
