### ISSUE TITLE
ERROR with OrientDB 2.2

### ISSUE THREAD

**Issue by stefpe** [Ostico/PhpOrient#71]
When I started to use this driver with OrientDB 2.1.* everything is working as it should, but with 2.2 it breaks because of Protocol version 34 is not supported.

Actually the solution is really simple, you need to pass the protocol version from your constants "32" during the two connect commands(server and database) and everything works.

I just removed these lines in OrientSocket Class, and now the constant protocol version was automatically transmitted in the both connect commands.

`            if( $protocol > $this->protocolVersion ){`
`                throw new PhpOrientWrongProtocolVersionException('Protocol version ' . $protocol . ' is not supported.');`
            `}`
`$this->protocolVersion = $protocol;`

Can you please fix this, because I really want to work with the newest version coming up.

Thank you in advance.

**Comment by andreyvk** [comment]
@stefpe this might not be as easy as just switching a value to *34* or even worse - removing a line that sets the protocol version internally in the library. New protocol might contain improvements/changes that might lead to wrong record handling and screw you DB at some point, if you do that. So be careful )) 

@Ostico needs to take a more thorough look I guess. I'm also looking forward to getting this new feat.

**Comment by smolinari** [comment]
Couldn't one just run the unit tests and if they pass, the protocol could be considered "functional" and more importantly, safe to use? The only thing there might not be is any additional features added to 34 would be missing. But, at least you'd know the driver still works properly with 2.2.

Scott

**Comment by andreyvk** [comment]
@smolinari very true

**Comment by stefpe** [comment]
I forked the project, changed the code and tried with version 2.1.* -> everything works!
Tried with version 2.2.0RC1 -> fails for tokens and some sql command tests.

**Comment by smolinari** [comment]
Ok. That would mean @Ostico would need to dig in and make the driver 2.2 ready. :smile: 

Scott

**Comment by luclanet** [comment]
+1

**Comment by RedactedProfile** [comment]
+1 very excited to use 2.2, but the driver need to support it :(

**Comment by Ostico** [comment]
Upgrading. Some issues on documentation slowed work. Will be updated as soon as possible. I apologize for the delay.

**Comment by andreyvk** [comment]
+1 for the update! woohoo!

**Comment by SimonSoftware** [comment]
+1 for the update

**Comment by GNSPS** [comment]
+1 for the update

**Comment by mamoit** [comment]
@Ostico Any news on the 2.2 compatibility?

**Comment by Ostico** [comment]
Hi all.
I started to work on that, but this month i'm really busy. I only upgraded the python driver at moment. I can continue starting from Wednesday.

**Comment by andreyvk** [comment]
@Ostico thanks for the reply. Eagerly waiting on the update. Good luck!

**Comment by smolinari** [comment]
@Ostico - If you need any support with documentation, doc proof reading, simple PHP programming tasks, please let me know. 

Scott

**Comment by RedactedProfile** [comment]
@Ostico similar, willing to offer help with the php driver, just let me know of a task or two that could help ease your load

**Comment by GNSPS** [comment]
@Ostico same here!

**Comment by SimonSoftware** [comment]
@Ostico me too!

**Comment by RedactedProfile** [comment]
a week later, any further update? Thank you 

cheers

**Comment by Metehan** [comment]
Today i tried to upgrade to 2.2 i also have this issue. 

Waiting not good but it's nice to see we have some community here, and i am not alone :)

**Comment by Ostico** [comment]
Updated
