### ISSUE TITLE
Packagist still on 1.2.3

### ISSUE THREAD

**Issue by RedactedProfile** [Ostico/PhpOrient#80]
Hi @Ostico 

Tried installing the new 1.2.4 through composer, but Packagist.org still seems to be on 1.2.3 as the newest version even today. 

Resolvable by doing dev-master, but that can be dangerous as you know :)

**Comment by Ostico** [comment]
Hi @RedactedProfile , now it is fixed.

Anyway dev-master is **always** stable.

**Comment by RedactedProfile** [comment]
Good to know! Neverless, feel comfortable with versioned releases :) :+1:
