### ISSUE TITLE
Version -1 received on the server side. Index could not be rebuilt

### ISSUE THREAD

**Issue by andreyvk** [Ostico/PhpOrient#89]
hi @Ostico ,

There's a rather serious issue with the driver on OrientDB 2.2. It seems that in some (or all?) cases during updates record version sent to the server is -1. This leads to some indexes not being built properly. Andrey Lomakin, from OrientDB team, has debugged the case and provided us with debugger data:

Java debugger:  http://i.imgur.com/qnskh9e.png
Request process: https://gist.github.com/laa/8f7d372554f07a8e75743d7da6987307

Frankly speaking I've known about the issue for a couple months now. Just couldn't identify where it was coming from as there were no errors/exceptions. Only with help of Andrey it was resolved. Please, take a look at this issue as it is a show stopper for moving to version 2.2.

**Comment by andreyvk** [comment]
Forgot to reference the initial issue: https://github.com/orientechnologies/orientdb/issues/7410

**Comment by andreyvk** [comment]
@Ostico hi, any chance to take a look at this?

**Comment by Ostico** [comment]
Of course, this week-end i will try to find and fix the issue

**Comment by Ostico** [comment]
Hi @andreyvk 
see:
https://github.com/Ostico/PhpOrient/commit/135de3526844a741f8f7a495c684be87d3ffd4c2#diff-59f8cc7280f092be6337004185a5fd63L91

https://github.com/Ostico/PhpOrient/commit/135de3526844a741f8f7a495c684be87d3ffd4c2#diff-000d131014a243a6df888342c5bd8b40L276

Let me know if it works.

**Comment by andreyvk** [comment]
@Ostico I've checked and I seems to work well :)) Cant thank you enough for this fix! It's been a very tough one. We'll continue testing for a week or so to see if there're any more problems that we can find, but it looks very promising now
