### ISSUE TITLE
3.0 Compatibility

### ISSUE THREAD

**Issue by usef911** [Ostico/PhpOrient#99]
Hi,
Are you releasing updates to support OrientDB 3.0?

Thanks

**Comment by futureglorydev** [comment]
its somehow works but unstable...
For instance, I have "unpack(): Type N: not enough input, need 4, have 0,  When execute sql:" on simple select from time to time. I have now reason why its so.. ((

**Comment by mtveerman** [comment]
Any progress? Is there a dev-branch somewhere?

**Comment by Ostico** [comment]
New version available.
